# Netlify Build Configuration
[build]
  # Build command for production
  command = "pnpm run build"
  
  # Directory to deploy (output of build)
  publish = "dist"
  
  # Redirect all requests to index.html for single-page application
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

# Build environment variables
[build.environment]
  NODE_VERSION = "20"
