# Netlify Build Configuration for Vite
# Note: Make sure to remove the Next.js plugin from Netlify UI:
# Site Settings → Build & deploy → Build plugins → Remove @netlify/plugin-nextjs

[build]
  # Build command - runs Vite build (tsc && vite build)
  command = "pnpm build"
  
  # Directory to deploy - Vite outputs to dist/
  publish = "dist"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build environment
[build.environment]
  NODE_VERSION = "20"
