# Netlify Build Configuration for Vite
# Note: Production deploys to GitHub Pages, Netlify is for PR previews only

[build]
  # Build command - runs Vite build (tsc && vite build)
  command = "pnpm build"
  
  # Directory to deploy - Vite outputs to dist/
  publish = "dist"
  
  # Ignore production builds - only build PR previews
  ignore = "git branch --show-current | grep -q '^main$'"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build environment
[build.environment]
  NODE_VERSION = "20"

# Deploy contexts - only build PR previews
[context.production]
  # Skip production deployments (handled by GitHub Pages)
  command = "echo 'Skipping production build - deployed via GitHub Pages'"
  publish = "public"

[context.deploy-preview]
  # Build PR previews
  command = "pnpm build"
  publish = "dist"

[context.branch-deploy]
  # Skip branch deployments (only PRs should build)
  command = "echo 'Skipping branch build - only PR previews enabled'"
