# Netlify Build Configuration for Vite
# IMPORTANT: In Netlify UI, set Production branch to "none" or a non-existent branch
# Production deploys via GitHub Pages, Netlify is ONLY for PR previews

[build]
  # Build command - runs Vite build (tsc && vite build)
  command = "pnpm build"
  
  # Directory to deploy - Vite outputs to dist/
  publish = "dist"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build environment
[build.environment]
  NODE_VERSION = "20"

# Deploy ONLY for PR previews
[context.deploy-preview]
  command = "pnpm build"
  publish = "dist"
