name: PR Checks

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'

jobs:
  lockfile-check:
    name: Verify lockfile is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Check lockfile is up to date
        run: |
          pnpm install --frozen-lockfile
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ ERROR: pnpm-lock.yaml is out of sync with package.json"
            echo ""
            echo "Please run 'pnpm install' locally and commit the updated lockfile."
            echo ""
            git status
            exit 1
          fi
          echo "✅ Lockfile is up to date"

  build-check:
    name: Verify build succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Check build output
        run: |
          if [ ! -d "out" ]; then
            echo "❌ ERROR: Build did not create 'out' directory"
            exit 1
          fi
          if [ ! -f "out/index.html" ]; then
            echo "❌ ERROR: Build did not create index.html"
            exit 1
          fi
          echo "✅ Build successful"

